### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by ippocratis** [alextran1502/immich#10]
trying to build on a raspbbery 400 running manjaro arm connected to eth0

running ```sudo docker-compose -f ./server/docker-compose.yml up -d``` 
gives 
```server error```
and
```
[2/4] Fetching packages...

info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/class-validator/-/class-validator-0.13.2.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ls 1 error occurred:
	* Status: The command '/bin/sh -c yarn install' returned a non-zero code: 1, Code: 1

```

**Comment by alextran1502** [comment]
I saw this on my build for ARM as well, I will investigate this.

**Comment by ippocratis** [comment]
recloned the repo 
and re-run docker-compose
also failed to build
had a ```server error``` again
and a ```debconf: delaying package configuration, since apt-utils is not installed``` error on Step 6/11 
on Step 7/11 : RUN npm install
```
 ---> Running in c2ed2180bd63
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.4.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.4.1>
npm notice Run `npm install -g npm@8.4.1` to update!
npm notice 
npm ERR! code 1
npm ERR! path /usr/src/app/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-3.13.0.tar.gz
npm ERR! * Downloading libtensorflow
npm ERR! /usr/src/app/node_modules/@tensorflow/tfjs-node/scripts/install.js:106
npm ERR!     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Unsupported system: cpu-linux-arm64
npm ERR!     at getPlatformLibtensorflowUri (/usr/src/app/node_modules/@tensorflow/tfjs-node/scripts/install.js:106:11)
npm ERR!     at downloadLibtensorflow (/usr/src/app/node_modules/@tensorflow/tfjs-node/scripts/install.js:139:15)
npm ERR!     at async run (/usr/src/app/node_modules/@tensorflow/tfjs-node/scripts/install.js:208:5)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-02-07T22_50_27_449Z-debug.log
1 error occurred:
	* Status: The command '/bin/sh -c npm install' returned a non-zero code: 1, Code: 1
```

**Comment by alextran1502** [comment]
Yes, Tensor Flow 2 right bow support 32bit system on Raspberry Pi but they don't have plan for 64bit yet. I will keep you update on this issue

**Comment by ippocratis** [comment]
i could try something like

https://github.com/photoprism/photoprism/blob/adeb18dc443f83d0d576e6f236587e6b277465d4/docker/scripts/install-tensorflow.sh

or

https://github.com/bitsy-ai/tensorflow-arm-bin

with prebuild tensorflow binaries for arm64?

**Comment by alextran1502** [comment]
You can try but I am afraid it won't work since the binary is built when installing the npm packages for the server. I hope they will be adding support for arm64 soon.

**Comment by ippocratis** [comment]
> You can try but I am afraid it won't work since the binary is built when installing the npm packages for the server. I hope they will be adding support for arm64 soon.


I see
So
Could I somehow edit your scripts to build tensorflow/tfjs-node from source?
I came upon this solution 
https://github.com/yhwang/node-red-contrib-tf-model
Thanks

**Comment by alextran1502** [comment]
Yes, please make a PR when you have it working, I will take a look

**Comment by alextran1502** [comment]
@ippocratis I rework the docker image, it is no longer requires TensorFlow for npm install. I will move TensorFlow to microservice architecture so other people can use different machine learning services if needed. You can reclone the repo and try build on ARM64

**Comment by ippocratis** [comment]
> @ippocratis I rework the docker image, it is no longer requires TensorFlow for npm install. I will move TensorFlow to microservice architecture so other people can use different machine learning services if needed. You can reclone the repo and try build on ARM64

thanks
apreciate it
the dockerfile builds fine now
but i have other issues
i cant access http://ip:2283 , https://ip:2284 nor can  create a user
lsogs say i didnt configure database properly

```
immich_server    | 
proxy_nginx      | 2022/02/10 10:31:38 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.32, server: , request: "GET / HTTP/1.1", upstream: "http://172.21.0.4:3000/", host: "192.168.1.24:2283"
proxy_nginx      | 192.168.1.32 - - [10/Feb/2022:10:31:38 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"
proxy_nginx      | 2022/02/10 10:31:38 [error] 22#22: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.32, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.21.0.4:3000/favicon.ico", host: "192.168.1.24:2283", referrer: "http://192.168.1.24:2283/"
proxy_nginx      | 192.168.1.32 - - [10/Feb/2022:10:31:38 +0000] "GET /favicon.ico HTTP/1.1" 502 559 "http://192.168.1.24:2283/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36" "-"
```

and


```
immich_postgres  | 2022-02-10 10:31:59.225 UTC [32] FATAL:  password authentication failed for user "immich"
immich_postgres  | 2022-02-10 10:31:59.225 UTC [32] DETAIL:  Role "immich" does not exist.
immich_postgres  | 	Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
immich_server    | [Nest] 29  - 02/10/2022, 10:31:59 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server    | error: password authentication failed for user "immich"
immich_server    |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)
immich_server    |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)
immich_server    |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)
immich_server    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)
immich_server    |     at Socket.emit (node:events:520:28)
immich_server    |     at addChunk (node:internal/streams/readable:315:12)
immich_server    |     at readableAddChunk (node:internal/streams/readable:289:9)
immich_server    |     at Socket.Readable.push (node:internal/streams/readable:228:10)
immich_server    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
immich_postgres  | 2022-02-10 10:32:02.520 UTC [33] FATAL:  password authentication failed for user "immich"
immich_postgres  | 2022-02-10 10:32:02.520 UTC [33] DETAIL:  Role "immich" does not exist.
immich_postgres  | 	Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```
my .env

```
NODE_ENV=development

# Database
DB_USERNAME=immich
DB_PASSWORD=immich
DB_DATABASE_NAME=immich

# Upload File Config
UPLOAD_LOCATION=./upload

# JWT SECRET
JWT_SECRET=immich
```

my docker-compose.yml

```
  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - immich_network
```
most likely i missed something
any ideas apreciated

btw since there are no bild errors now should i close this issue and open a new one?

**Comment by ippocratis** [comment]
thanks Dockerfile buils fine now
apreciate it
