### ISSUE TITLE
[BUG] Android can't login

### ISSUE THREAD

**Issue by fuji246** [alextran1502/immich#101]
**Describe the bug**

Can't login, see the logcat output below.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Android 11

**Additional context**

```
03-31 21:31:31.558  7692  7719 I flutter : pint server at url http://10.0.0.223:2283/server-info/ping
03-31 21:31:36.539   735   787 E LightsService: Light requested not available on this device. 2
03-31 21:31:36.850   735   893 E LightsService: Light requested not available on this device. 2
03-31 21:31:39.011  7692  7719 I flutter : DioError: null
03-31 21:31:39.012  7692  7719 I flutter : Error getAllAsset  type 'Null' is not a subtype of type 'List<dynamic>'
03-31 21:31:39.013  7692  7719 I flutter : DioError: null
03-31 21:31:39.014  7692  7719 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'Response<dynamic>'
03-31 21:31:39.014  7692  7719 E flutter : #0      ServerInfoService.getServerVersion (package:immich_mobile/shared/services/server_info.service.dart:23)
03-31 21:31:39.014  7692  7719 E flutter : <asynchronous suspension>
03-31 21:31:39.014  7692  7719 E flutter : #1      ServerInfoNotifier.getServerVersion (package:immich_mobile/shared/providers/server_info.provider.dart:28)
03-31 21:31:39.014  7692  7719 E flutter : <asynchronous suspension>
03-31 21:31:39.014  7692  7719 E flutter : 
03-31 21:31:40.498  7692  7719 I flutter : [PING SERVER] DioError: null - DioError [DioErrorType.connectTimeout]: Connecting timed out [0ms]
03-31 21:31:40.498  7692  7719 I flutter : Source stack:
03-31 21:31:40.499  7692  7719 I flutter : #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
03-31 21:31:40.499  7692  7719 I flutter : #1      DioMixin.request (package:dio/src/dio_mixin.dart:468)
03-31 21:31:40.499  7692  7719 I flutter : #2      DioMixin.get (package:dio/src/dio_mixin.dart:55)
03-31 21:31:40.499  7692  7719 I flutter : #3      NetworkService.pingServer (package:immich_mobile/shared/services/network.service.dart:91)
03-31 21:31:40.499  7692  7719 I flutter : #4      AuthenticationNotifier.login (package:immich_mobile/modules/login/providers/authentication.provider.dart:49)
03-31 21:31:40.500  7692  7719 I flutter : #5      LoginButton.build.<anonymous closure> (package:immich_mobile/modules/login/ui/login_form.dart:122)
03-31 21:31:40.500  7692  7719 I flutter : #6      LoginButton.build.<anonymous closure> (package:immich_mobile/modules/login/ui/login_form.dart:116)
03-31 21:31:40.500  7692  7719 I flutter : #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989)
03-31 21:31:40.500  7692  7719 I flutter : #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
03-31 21:31:40.500  7692  7719 I flutter : #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
03-31 21:31:40.500  7692  7719 I flutter : #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
03-31 21:31:40.501  7692  7719 I flutter : #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230)
03-31 21:31:40.501  7692  7719 I flutter : #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563)
03-31 21:31:40.501  7692  7719 I flutter : #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94)
03-31 21:31:40.501  7692  7719 I flutter : #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139)
03-31 21:31:40.502  7692  7719 I flutter : #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539)
03-31 21:31:40.502  7692  7719 I flutter : #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137)
03-31 21:31:40.502  7692  7719 I flutter : #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123)
03-31 21:31:40.502  7692  7719 I flutter : #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439)
03-31 21:31:40.502  7692  7719 I flutter : #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419)
03-31 21:31:40.502  7692  7719 I flutter : #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322)
03-31 21:31:40.503  7692  7719 I flutter : #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
03-31 21:31:40.503  7692  7719 I flutter : #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
03-31 21:31:40.503  7692  7719 I flutter : #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
03-31 21:31:40.503  7692  7719 I flutter : #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
03-31 21:31:40.503  7692  7719 I flutter : #25     _rootRunUnary (dart:async/zone.dart:1442)
03-31 21:31:40.503  7692  7719 I flutter : #26     _CustomZone.runUnary (dart:async/zone.dart:1335)
03-31 21:31:40.504  7692  7719 I flutter : #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
03-31 21:31:40.504  7692  7719 I flutter : #28     _invoke1 (dart:ui/hooks.dart:170)
03-31 21:31:40.504  7692  7719 I flutter : #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
03-31 21:31:40.504  7692  7719 I flutter : #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)
03-31 21:31:40.504  7692  7719 I flutter : 
03-31 21:31:41.565  7692  7719 I flutter : [PING SERVER] DioError: null - DioError [DioErrorType.connectTimeout]: Connecting timed out [0ms]
03-31 21:31:41.565  7692  7719 I flutter : Source stack:
03-31 21:31:41.566  7692  7719 I flutter : #0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
03-31 21:31:41.566  7692  7719 I flutter : #1      DioMixin.request (package:dio/src/dio_mixin.dart:468)
03-31 21:31:41.566  7692  7719 I flutter : #2      DioMixin.get (package:dio/src/dio_mixin.dart:55)
03-31 21:31:41.566  7692  7719 I flutter : #3      NetworkService.pingServer (package:immich_mobile/shared/services/network.service.dart:91)
03-31 21:31:41.566  7692  7719 I flutter : #4      AuthenticationNotifier.login (package:immich_mobile/modules/login/providers/authentication.provider.dart:49)
03-31 21:31:41.567  7692  7719 I flutter : #5      LoginButton.build.<anonymous closure> (package:immich_mobile/modules/login/ui/login_form.dart:122)
03-31 21:31:41.567  7692  7719 I flutter : #6      LoginButton.build.<anonymous closure> (package:immich_mobile/modules/login/ui/login_form.dart:116)
03-31 21:31:41.567  7692  7719 I flutter : #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989)
03-31 21:31:41.567  7692  7719 I flutter : #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
03-31 21:31:41.567  7692  7719 I flutter : #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
03-31 21:31:41.568  7692  7719 I flutter : #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
03-31 21:31:41.568  7692  7719 I flutter : #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230)
03-31 21:31:41.568  7692  7719 I flutter : #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563)
03-31 21:31:41.569  7692  7719 I flutter : #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94)
03-31 21:31:41.569  7692  7719 I flutter : #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139)
03-31 21:31:41.569  7692  7719 I flutter : #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539)
03-31 21:31:41.569  7692  7719 I flutter : #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137)
03-31 21:31:41.569  7692  7719 I flutter : #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123)
03-31 21:31:41.570  7692  7719 I flutter : #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:439)
03-31 21:31:41.570  7692  7719 I flutter : #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419)
03-31 21:31:41.570  7692  7719 I flutter : #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322)
03-31 21:31:41.570  7692  7719 I flutter : #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
03-31 21:31:41.570  7692  7719 I flutter : #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
03-31 21:31:41.570  7692  7719 I flutter : #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
03-31 21:31:41.570  7692  7719 I flutter : #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
03-31 21:31:41.570  7692  7719 I flutter : #25     _rootRunUnary (dart:async/zone.dart:1442)
03-31 21:31:41.570  7692  7719 I flutter : #26     _CustomZone.runUnary (dart:async/zone.dart:1335)
03-31 21:31:41.570  7692  7719 I flutter : #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
03-31 21:31:41.570  7692  7719 I flutter : #28     _invoke1 (dart:ui/hooks.dart:170)
03-31 21:31:41.570  7692  7719 I flutter : #29     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
03-31 21:31:41.570  7692  7719 I flutter : #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)
03-31 21:31:41.571  7692  7719 I flutter : 
03-31 21:31:41.949   735   787 E LightsService: Light requested not available on this device. 2

```

**Comment by alextran1502** [comment]
Can you navigate to http://10.0.0.223:2283/server-info/ping on your web browser and show me the response on the website?

**Comment by fuji246** [comment]
It responded with `{"res":"pong"}`. The Android APP login succeed once, and I don't see any photos show up, so I restart it, then it can't login again.

**Comment by alextran1502** [comment]
Maybe I ask which APK release and which server version did you use?

When you restart the server and try to login again, does it work?

**Comment by fuji246** [comment]
I just download everything yesterday on github page, so it should be the latest. The commit is "fc1acf6f012c415df8c776ecea679c6f348dd921". 

Tried to restart server and client, neither works for me. Any founding in the Android log above?

**Comment by alextran1502** [comment]
Not yet, I will have to set up an Android 11 simulator and try to reproduce this issue.

**Comment by fuji246** [comment]
Wifi connected to another subnetwork different with the server.
