### ISSUE TITLE
[BUG] 500 JSON error after install

### ISSUE THREAD

**Issue by PDXUser** [alextran1502/immich#242]
After fresh install following the readme.md here, I get a JSON error upon loading the URL for the first time:
```
500

Unexpected token < in JSON at position 0

SyntaxError: Unexpected token < in JSON at position 0
```

The error in the web server container is as follows:
 
```
today at 10:43:51 AMListening on 0.0.0.0:3000
today at 10:43:55 AMSyntaxError: Unexpected token < in JSON at position 0
today at 10:43:55 AM    at JSON.parse (<anonymous>)
today at 10:43:55 AM    at Proxy.<anonymous> (file:///usr/src/app/build/server/index.js:1586:29)
today at 10:43:55 AM    at processTicksAndRejections (node:internal/process/task_queues:96:5)
today at 10:43:55 AM    at async load (file:///usr/src/app/build/server/entries/pages/index.svelte.js:6:25)
today at 10:43:55 AM    at async load_node (file:///usr/src/app/build/server/index.js:1605:14)
today at 10:43:55 AM    at async respond$1 (file:///usr/src/app/build/server/index.js:1844:20)
today at 10:43:55 AM    at async resolve (file:///usr/src/app/build/server/index.js:2182:105)
today at 10:43:55 AM    at async Object.handle (file:///usr/src/app/build/server/chunks/hooks-31102541.js:7:12)
today at 10:43:55 AM    at async respond (file:///usr/src/app/build/server/index.js:2139:22)
today at 10:43:55 AM    at async Array.ssr (file:///usr/src/app/build/handler-edaaddc2.js:841:3)

```
I do get the "New version" announcement dialog which works, but it does not show the current version of the installed server.

The Machine learning, Microservice, Server, postgres and redis containers do not show any errors.

**Comment by PDXUser** [comment]
```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres  
DB_DATABASE_NAME=immich





###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis





###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/mnt/Storage/Gallery




###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=REDACTED FOR SHARING!!!  




###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=




###################################################################################
# WEB
###################################################################################

# This is the URL of your vm/server where you host Immich, so that the web frontend
# know where can it make the request to.
# For example: If your server IP address is 10.1.11.50, the environment variable will
# be VITE_SERVER_ENDPOINT=http://10.1.11.50:2283
# !CAUTION! THERE IS NO FORWARD SLASH AT THE END

VITE_SERVER_ENDPOINT=http://192.168.1.161
```

**Comment by PDXUser** [comment]
Ahhh thanks!  I guess I was confused by the statement about the IP address, I though it would auto config the 2283 after the fact.  Good to know!  I was able to register now and get to exploring your product.  Thanks!
