### ISSUE TITLE
[BUG] unable to access from external internet via nginx proxy manager

### ISSUE THREAD

**Issue by spupuz** [alextran1502/immich#270]
i i try to access from external i can login but then page is empty and do not shows anything:

![image](https://user-images.githubusercontent.com/1721792/175897207-b58dac9f-2d8b-4e76-9359-3a2378b1b78f.png)

and administration page give this error

```
500
Failed to fetch
TypeError: Failed to fetch
    at et (https://immich.xxxxxx.duckdns.org/_app/chunks/status-box-0bf9b254.js:1:788)
    at Ce (https://immich.xxxxxxx.duckdns.org/_app/chunks/status-box-0bf9b254.js:1:906)
    at yt (https://immich.spupuz.xxxxxx.org/_app/pages/admin/index.svelte-f8c0fb41.js:1:15614)
    at Q (https://immich.xxxxxx.duckdns.org/_app/start-e47c71ce.js:1:17890)
    at Ne (https://immich.xxxxxx.duckdns.org/_app/start-e47c71ce.js:1:19117)
    at async me (https://immich.xxxxxx.duckdns.org/_app/start-e47c71ce.js:1:14557)
    at async we (https://immich.xxxxxx.duckdns.org/_app/start-e47c71ce.js:1:20938)
```

**Comment by zackpollard** [comment]
Resolved in discord, closing issue
